version: '3.3'
services:
  db:
    image: postgres
    env_file:
      - database.env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - prismo-postgres:/var/lib/postgresql/data

volumes:
  prismo-postgres: